os: linux
dist: trusty
sudo: false
addons:
   apt:
      packages:
      - luarocks
skip_cleanup: true
install:
- luarocks install --local moonscript
- $(luarocks path)
- export PATH="$HOME/.luarocks/bin/:$PATH"
script:
- for file in *.moon; do moonc -o "template/${file%.moon}.lua" "$file"; done
- zip msp.mpackage template/*
