os: linux
dist: trusty
sudo: false
addons:
   apt:
      packages:
      - luarocks
install:
- luarocks install --local moonscript
- $(luarocks path)
- export PATH="$HOME/.luarocks/bin/:$PATH"
script:
- moonc *.moon
